In [1]:
# import libraries
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv('housing_cleaned.csv')

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,household_rooms
0,-122.23,37.88,41.0,6.781058,4.867534,5.777652,4.844187,8.3252,452600.0,NEAR BAY,1.399834
1,-122.22,37.86,21.0,8.867850,7.009409,7.784057,7.037906,8.3014,358500.0,NEAR BAY,1.260013
2,-122.24,37.85,52.0,7.291656,5.252273,6.208590,5.181784,7.2574,352100.0,NEAR BAY,1.407171
3,-122.25,37.85,52.0,7.150701,5.463832,6.326149,5.393628,5.6431,341300.0,NEAR BAY,1.325768
4,-122.25,37.85,52.0,7.395108,5.638355,6.338594,5.560682,3.8462,342200.0,NEAR BAY,1.329892
...,...,...,...,...,...,...,...,...,...,...,...
20425,-121.09,39.48,25.0,7.418181,5.926926,6.740519,5.802118,1.5603,78100.0,INLAND,1.278530
20426,-121.21,39.49,18.0,6.548219,5.017280,5.877736,4.744932,2.5568,77100.0,INLAND,1.380045
20427,-121.22,39.43,17.0,7.720905,6.186209,6.915723,6.073045,1.7000,92300.0,INLAND,1.271340
20428,-121.32,39.43,18.0,7.528869,6.016157,6.609349,5.857933,1.8672,84700.0,INLAND,1.285243
20429,-121.24,39.37,16.0,7.932362,6.424869,7.235619,6.274762,2.3886,89400.0,INLAND,1.264169

# Feature-Target Splitting
We separate the dataset into X and Y to distinguish between the data we learn from and the value we want to predict.

In [4]:
x = df.drop(['median_house_value'],axis = 1)
y = df['median_house_value']

# Train-Test Splitting
We split the data into 4 subsets to train the model and then evaluate its performance on unseen data.

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

train_data = x_train.join(y_train)
test_data = x_test.join(y_test)

- (X_train, y_train) used to train the model.
- (X_test, y_test) used to "evaluate" the model.
- (train_data, test_data) used for applying transformations each one separately

# Transformation After Splitting

Encoding Transformation For "ocean_proximity"

In [6]:
train_data = train_data.join(pd.get_dummies(train_data.ocean_proximity,dtype= int)).drop(['ocean_proximity'],axis = 1)
test_data = test_data.join(pd.get_dummies(test_data.ocean_proximity,dtype= int)).drop(['ocean_proximity'],axis = 1)

# Avoiding expected error 
test_data = test_data.reindex(columns = train_data.columns, fill_value=0)

Check the result

In [7]:
train_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,household_rooms,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
17519,-121.84,37.29,4.0,7.985484,6.475433,7.484930,6.501290,4.3851,1.228292,160400.0,1,0,0,0,0
5644,-118.26,34.23,33.0,7.498870,5.717028,6.732211,5.710427,5.4306,1.313189,326600.0,1,0,0,0,0
5320,-118.39,34.03,28.0,7.451822,6.285998,7.057898,6.177944,3.2228,1.206198,232500.0,1,0,0,0,0
14783,-117.01,32.67,17.0,7.749322,5.855072,7.026427,5.823046,5.5510,1.330802,266900.0,0,0,0,0,1
15222,-117.24,33.38,16.0,7.934872,6.265301,7.436617,6.248043,3.6680,1.269977,171200.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12324,-115.58,33.88,21.0,7.057898,5.645447,6.586172,5.231109,3.1827,1.349216,71700.0,0,1,0,0,0
10371,-117.69,33.60,16.0,7.698936,5.976351,7.195937,5.998937,3.4750,1.283383,279500.0,1,0,0,0,0
4554,-118.28,34.05,44.0,6.876265,5.953243,7.498870,5.929589,1.4801,1.159653,212500.0,1,0,0,0,0
16838,-122.29,37.55,27.0,8.240121,6.774224,7.716015,6.765039,4.3900,1.218045,270100.0,0,0,0,0,1
13828,-116.88,34.25,11.0,6.993933,5.293305,5.442418,4.510860,4.9643,1.550466,176000.0,0,1,0,0,0

In [8]:
test_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,household_rooms,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
17261,-120.45,34.65,27.0,7.720462,5.948035,7.088409,5.953243,3.3203,1.296850,134700.0,0,0,0,0,1
437,-122.29,37.85,52.0,6.169611,4.787492,5.389072,4.672829,2.5682,1.320316,120000.0,0,0,0,1,0
8092,-118.11,33.81,37.0,7.435438,5.638355,6.655440,5.605802,6.2187,1.326383,257900.0,1,0,0,0,0
10650,-117.86,33.65,4.0,8.193953,6.643790,7.190676,6.572283,5.4284,1.246744,500001.0,1,0,0,0,0
17141,-119.59,34.39,35.0,6.434547,5.141664,5.631212,4.941642,3.6969,1.302107,335000.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,-122.36,37.94,26.0,7.340187,5.840642,6.915723,5.826000,1.3365,1.259902,72900.0,0,0,0,1,0
9238,-122.50,37.97,25.0,8.783703,7.551187,8.685754,7.502738,2.7273,1.170733,187500.0,0,0,0,1,0
17292,-119.85,34.40,14.0,7.744137,6.478510,8.652423,6.423247,2.1652,1.205642,37500.0,0,0,0,0,1
6339,-118.02,34.12,37.0,7.719130,5.888878,6.897705,5.799093,6.1536,1.331093,366000.0,0,1,0,0,0
5365,-118.41,34.03,20.0,8.383662,7.179308,7.680637,7.078342,3.6019,1.184410,463600.0,1,0,0,0,0

# Training The Model

In [9]:
x_train, y_train = train_data.drop(['median_house_value'], axis= 1), train_data['median_house_value']
x_test, y_test = test_data.drop(['median_house_value'], axis= 1), test_data['median_house_value']

In [10]:
reg = LinearRegression()

reg.fit(x_train,y_train)

LinearRegression()

In [11]:
reg.score(x_test,y_test)

0.6791426493548769

In [12]:
forest = RandomForestRegressor()

forest.fit(x_train,y_train)

RandomForestRegressor()

In [13]:
forest.score(x_test,y_test)

0.821924198226198